### ISSUE TITLE
ReferenceError: checkAndConvertPoint is not defined

### ISSUE THREAD

**Issue by pito-svk** [moshen/node-googlemaps#127]
When running tests (in tape) or just require('googlemaps') (in REPL) I got this error

```
ReferenceError: checkAndConvertPoint is not defined
    at Object.<anonymous> ({MY_PATH}/node_modules/googlemaps/lib/index.js:200:77)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at repl:1:1
    at sigintHandlersWrap (vm.js:32:31)


```

```javascript
// googlemaps/lib/index.js:201:15
GoogleMapsAPI.prototype.checkAndConvertArrayOfPoints = checkAndConvertPoint = function(input) {
```

I am using node v6.3.1
and node-googlemaps version is 1.11.1

Please check, thanks.

**Comment by pito-svk** [comment]
Found the issue, I was using strict mode.
