### ISSUE TITLE
Maximum URL size

### ISSUE THREAD

**Issue by PedroFabrino** [moshen/node-googlemaps#138]
According to Google's documentation for Static Map, the max size for url is 8192 characters, https://developers.google.com/maps/documentation/static-maps/intro#url-size-restriction.

But, when building an static map with gm.staticMap(params), 
I get the following error:
Error: Request too long for google to handle (2048 characters).
    at module.exports (.../node_modules/googlemaps/lib/utils/makeRequest.js:63:13)
    at module.exports [as staticMap] (.../node_modules/googlemaps/lib/staticMap.js:116:10)

It's thrown an error before making a request for google, so it's internal.

Could it be fixed? Or should I make a fork for doing so? Or is there a reason as not working?

**Comment by chiu0602** [comment]
The setting is in lib/config/constants.json MAX_REQUEST_LENGTHS, you may modify and test it.

**Comment by ClaaziX** [comment]
if there are only 2045 chars and the lmit is 8192... why is it throwing this error at all?

**Comment by PedroFabrino** [comment]
Because the error is being thrown by the node-googlemaps, and not by google itself.

**Comment by jitendra-kr** [comment]
Yes i am facing same problem. I created an issue also for the same.

**Comment by twindual** [comment]
In the /lib/requests/contants.json file it has the max values listed as 2048.

We could up that to 8192 and solve the issue.

  "MAX_REQUEST_LENGTHS": {
    "directions":          2048,
    "distance-matrix":     2048,
    "elevation":           -1,
    "geocode":             2048,
    "place-details":       2048,
    "place-search-nearby": 2048,
    "place-search-text":   2048,
    "place-autocomplete":  2048,
    "reverse-geocode":     2048,
    "static-map":          2048,
    "timezone":            2048,
    "street-view":         2048
  },
